workflows:
  flutter-ios:
    name: Flutter iOS Build
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
